### ISSUE TITLE
Confusing warning message

### ISSUE THREAD

**Issue by andyndang** [whylabs/whylabs-toolkit#51]
https://github.com/whylabs/whylabs-toolkit/blob/29936c9a40202ff95b5b7cdb53a0db4bb009ef4a/whylabs_toolkit/helpers/monitor_helpers.py#L42

Got this when I tried to create a monitor first time:

```
WARNING:whylabs_toolkit.helpers.monitor_helpers:Could not find a monitor with id brightness-constraint for model-23.Did you set a correct WHYLABS_API_KEY?
```

It's very confusing since this is a monitor creation.

**Comment by murilommen** [comment]
closing this as it's no longer the case with the current version of the toolkit
